name: hexlet-ci-app
on: [push]
jobs:
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: make setup
      - run: make lint
      - run: make test
        env: 
          SNYC_TOKEN: ${{secrets.HEXLET_CI_APP_SECRET}}
